<a href="https://colab.research.google.com/github/gtsolo/MyCode/blob/main/mypython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1=np.array([0.5,3,30])   #一维数组
arr2=np.array([[1,2,3,4],[5,6,7,8]])   #二维数组
print(arr2)
print(arr1)
print(type(arr1))
print(type(arr2))

[[1 2 3 4]
 [5 6 7 8]]
[ 0.5  3.  30. ]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [3]:
arr1

array([ 0.5,  3. , 30. ])

In [4]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2[1][2]

7

In [6]:
print(arr1.shape)

(3,)


In [7]:
print(arr2.ndim)
print(arr2.dtype)
print(arr1.dtype)
print(arr2.shape)

2
int64
float64
(2, 4)


#数组特点

In [8]:
list1 = [0.3,0.5,3.5]
arr1 = np.array([0.3,0.5,3.5])

print(list1)
print(arr1)

print([i**2 for i in list1])
print(arr1**2)

[0.3, 0.5, 3.5]
[0.3 0.5 3.5]
[0.09, 0.25, 12.25]
[ 0.09  0.25 12.25]


In [9]:
arr3 = np.arange(0,10)
arr4 =np.arange(10)
arr5 = np.arange(0,1,0.1)
print(arr4)
print(arr3)
print(arr5)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [10]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [11]:
arr6 =np.linspace(0,1,10)
print(arr6)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [12]:
arr7 = np.zeros([2,4,5])
print(arr7)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [19]:
arr8 = np.array([3,4,5],dtype=np.float64)
print(arr8)
print(arr8.dtype)
arr8[0]=1.2

print(np.int32(arr8))
print(arr8)

[3. 4. 5.]
float64
[1 4 5]
[1.2 4.  5. ]


#生成随机数

In [26]:
print(np.random.random(10))  #无约束条件下的随机数
np.random.rand(10)   #均匀分布的随机数
np.random.rand(3,4)   
np.random.randn(2,3,4)  #指定随机数正态分布

[0.81741824 0.3339259  0.38299641 0.92034885 0.93212923 0.13243518
 0.74513609 0.74591418 0.9664202  0.25025354]


array([[0.16064574, 0.71281428, 0.59706979, 0.22042949],
       [0.40208543, 0.05916989, 0.11278958, 0.7551737 ],
       [0.47107269, 0.707645  , 0.39360547, 0.63092987]])

#数组索引

In [49]:
#一维数组单个索引
print(arr1)
print(arr1[2])
print(arr1[-3:-1])
res1 = arr1[2]
#一维数组多个索引   
res2 = arr1[-3:-1]
print(res1,res1.shape)

print(res2,res2.shape)

[0.3 0.5 3.5]
3.5
[0.3 0.5]
3.5 ()
[0.3 0.5] (2,)


In [55]:
#逻辑索引
arr1=np.array([2.3,1.8,6.5])
print(arr1)
print(arr1[[False,False,True]])
index=arr1>2
print(arr1[index])


[2.3 1.8 6.5]
[6.5]
[2.3 6.5]


In [77]:
#多维数组索引

arr3 = np.arange(0,12).reshape([3,4])
print(arr3)
print(arr3[2,3])
print(arr3[2,0:])
print(arr3[:,0])
print(arr3[1:3,1:3])
print("--------")
print(arr3[2:,:])
print(arr3[arr3[:,0]>5,:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
11
[ 8  9 10 11]
[0 4 8]
[[ 5  6]
 [ 9 10]]
--------
[[ 8  9 10 11]]
[[ 8  9 10 11]]


#修改数组元素

In [81]:
arr3 =np.arange(0,12).reshape([3,4])
print(arr3)
arr3[0,0]=15
print(arr3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[15  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [94]:
#求解距离坐标
n = 100
x =np.linspace(1,1000,n)
y = np.linspace(1,1000,n)
dist=np.zeros([n,n])

dist[0,1] = np.sqrt((x[0]-x[1])**2+(y[0]-y[1])**2)
for i in range(n):
  for j in range(n):
    dist[i,j] = np.sqrt((x[i]-x[j])**2+(y[i]-y[j])**2)
print(x)
print(y)
print(dist)

[   1.           11.09090909   21.18181818   31.27272727   41.36363636
   51.45454545   61.54545455   71.63636364   81.72727273   91.81818182
  101.90909091  112.          122.09090909  132.18181818  142.27272727
  152.36363636  162.45454545  172.54545455  182.63636364  192.72727273
  202.81818182  212.90909091  223.          233.09090909  243.18181818
  253.27272727  263.36363636  273.45454545  283.54545455  293.63636364
  303.72727273  313.81818182  323.90909091  334.          344.09090909
  354.18181818  364.27272727  374.36363636  384.45454545  394.54545455
  404.63636364  414.72727273  424.81818182  434.90909091  445.
  455.09090909  465.18181818  475.27272727  485.36363636  495.45454545
  505.54545455  515.63636364  525.72727273  535.81818182  545.90909091
  556.          566.09090909  576.18181818  586.27272727  596.36363636
  606.45454545  616.54545455  626.63636364  636.72727273  646.81818182
  656.90909091  667.          677.09090909  687.18181818  697.27272727
  707.36363636

#数组形态变化

In [103]:
arr4 =np.arange(1,13)
print(arr4)
print(arr4.reshape([3,4]))
print(arr4.reshape([4,3]))
arr5 = arr4.reshape([3,4])
print(arr5)
print(arr5.ravel())   #数组展平
arr6=arr5.flatten()   #数组展平
arr6=arr5.flatten('F')
print(arr6)
print('-----------')
arr7=arr4.reshape([3,4])
print(np.vstack([arr5,arr7]))

print(np.hstack([arr5,arr7]))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  5  9  2  6 10  3  7 11  4  8 12]
-----------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]]
