<a href="https://colab.research.google.com/github/gtsolo/MyCode/blob/main/mypython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([0.5,3,30])   #一维数组
arr2=np.array([[1,2,3,4],[5,6,7,8]])   #二维数组
print(arr2)
print(arr1)
print(type(arr1))
print(type(arr2))

[[1 2 3 4]
 [5 6 7 8]]
[ 0.5  3.  30. ]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
arr1

array([ 0.5,  3. , 30. ])

In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2[1][2]

7

In [ ]:
print(arr1.shape)

(3,)


In [ ]:
print(arr2.ndim)
print(arr2.dtype)
print(arr1.dtype)
print(arr2.shape)

2
int32
float64
(2, 4)


#数组特点

In [ ]:
list1 = [0.3,0.5,3.5]
arr1 = np.array([0.3,0.5,3.5])

print(list1)
print(arr1)

print([i**2 for i in list1])
print(arr1**2)

[0.3, 0.5, 3.5]
[0.3 0.5 3.5]
[0.09, 0.25, 12.25]
[ 0.09  0.25 12.25]


In [ ]:
arr3 = np.arange(0,10)
arr4 =np.arange(10)
arr5 = np.arange(0,1,0.1)
print(arr4)
print(arr3)
print(arr5)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [ ]:
arr6 =np.linspace(0,1,10)
print(arr6)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
arr7 = np.zeros([2,4,5])
print(arr7)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


#掌握Numpy矩阵于通用函数

In [ ]:
import numpy as np
matr1 = np.mat("1,2,3;4,5,6;7,8,9")
print(matr1)
print(type(matr1))

matr2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(matr2)
print(type(matr2))
#print(np.bmat('matr1 matr2;matr1,matr2'))  #矩阵拼接
print(matr1.T)   #矩阵转置

print(matr1.H)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
arr1 = np.array([0.2,0.4,0.6])
list1 = [0.2,0.4,0.6]
arr2 = np.array([0.2,0.6,0.8])

print(arr1+1)
#print(list1+1)  非法操作
print(arr1*2)
print(list1*2)
print(arr1+arr2)
print(arr2*arr2)

print(arr1>0.2)

print(np.any(arr1>0.2))  #逻辑or
print(np.all(arr1>0.2))   #逻辑and



[1.2 1.4 1.6]
[0.4 0.8 1.2]
[0.2, 0.4, 0.6, 0.2, 0.4, 0.6]
[0.4 1.  1.4]
[0.04 0.36 0.64]
[False  True  True]
True
False


In [17]:
arr3 = np.arange(1,13).reshape([4,3])
arr4 = np.array([1,2,3])
arr5 = np.array([[1],[2],[3],[4]])
print(arr3)
print(arr4)
print(arr3+arr4)
print(arr3+arr5)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


#利用numpy进行数据分析

In [35]:
#保存为二进制文件
import numpy as np
arr1 =np.arange(1,13).reshape([4,3])
arr2 = np.arange(1,13)
print(arr1)
np.save('/content/arr1.npy',arr1)
ar1= np.load('/content/arr1.npy')
print(ar1)
np.savez('/content/arr1$2.npz',arr1,arr2)  #保存多个数据
ar2 = np.load('/content/arr1$2.npz')
print(ar2)    #查看有哪些数组对象
ar2.files #查看有哪些数组对象
ar2['arr_0']  #查看文件中具体数据对象

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
#读写文本文件txt
np.savetxt('/content/arr1.txt',arr1,delimiter=',')  #保存
np.loadtxt('/content/arr1.txt',delimiter=',')     #读取

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [61]:
#使用数组来统计
arr3 = np.random.randint(1,10,(3,4))
print(arr3)
arr3.sort(axis=1)  #按行排序
print(arr3)
print(arr3.argsort(axis=1))  #返回下标
print(np.tile(arr3,3))   #数组元素复制
print(np.repeat(arr3,2,axis=0)) #数组元素复制

print(arr3.mean())  #统计所有元素均值
print(arr3.mean(axis=0))
print(arr3.max(axis=1))
arr3.argmax(axis=0)   #找出每列最大值的位置

arr3.std(axis=0)

[[7 9 7 2]
 [7 6 5 7]
 [7 3 5 4]]
[[2 7 7 9]
 [5 6 7 7]
 [3 4 5 7]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[2 7 7 9 2 7 7 9 2 7 7 9]
 [5 6 7 7 5 6 7 7 5 6 7 7]
 [3 4 5 7 3 4 5 7 3 4 5 7]]
[[2 7 7 9]
 [2 7 7 9]
 [5 6 7 7]
 [5 6 7 7]
 [3 4 5 7]
 [3 4 5 7]]
5.75
[3.33333333 5.66666667 6.33333333 7.66666667]
[9 7 7]


array([1.24721913, 1.24721913, 0.94280904, 0.94280904])